# Generated by Django 5.2.17 on 2026-08-17 20:01

import django.db.models.deletion
import expenses.payout_models
import expenses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(db_index=True)),
                ('card_name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_verification', 'Ожидает проверки'), ('verified', 'Подтверждён'), ('rejected', 'Отклонён'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('canceled', 'Отменён')], default='pending_verification', max_length=32)),
                ('original_file', models.FileField(blank=True, null=True, storage=expenses.storage.private_expense_storage, upload_to=expenses.payout_models.invoice_original_path)),
                ('public_file', models.FileField(blank=True, null=True, upload_to=expenses.payout_models.invoice_public_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('submitted_by_id', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('publish_receipt', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('clinic', 'Клиника'), ('supplier', 'Поставщик')], default='clinic', max_length=32)),
                ('bin_hash', models.CharField(max_length=64, unique=True)),
                ('bin_masked', models.CharField(max_length=32)),
                ('bin_encrypted', models.TextField()),
                ('iban_masked', models.CharField(max_length=32)),
                ('iban_encrypted', models.TextField()),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('verified', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_id', models.IntegerField(blank=True, null=True)),
                ('verification_reason', models.TextField(blank=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses_verifiedorganization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='expenses.invoice')),
            ],
            options={
                'db_table': 'expenses_invoicedecisionevent',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('status', models.CharField(choices=[('requested', 'Запрошена'), ('processing', 'В обработке'), ('succeeded', 'Выполнена'), ('failed', 'Ошибка'), ('canceled', 'Отменена')], default='requested', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_payout_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('requested_by_id', models.IntegerField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='expenses.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='expenses.verifiedorganization')),
            ],
            options={
                'db_table': 'expenses_payout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='expenses.payout')),
            ],
            options={
                'db_table': 'expenses_payoutevent',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedPayoutCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='expenses.payout')),
            ],
            options={
                'db_table': 'expenses_processedpayoutcallback',
            },
        ),
        migrations.CreateModel(
            name='OrganizationVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='expenses.verifiedorganization')),
            ],
            options={
                'db_table': 'expenses_organizationverificationevent',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='expenses.verifiedorganization'),
        ),
    ]
