# Generated by Django 6.0.6 on 2026-06-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='success', max_length=16)),
                ('payment_method', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='cards.fundraisingcard')),
            ],
        ),
    ]
