from django.urls import path

from .comment_views import ExpenseCommentEditView
from .views import (
    AdminExpenseListView,
    CardExpenseListCreateView,
    CardPublicExpenseReportView,
    ExpenseApproveView,
    ExpenseCancelView,
    ExpenseDetailView,
    ExpenseOriginalView,
    ExpenseRejectView,
    ExpenseRequestRevisionView,
    ExpenseSubmitView,
    InternalMarkPaidView,
    InternalReconcileView,
    InternalTotalsView,
    ModerationExpenseListView,
)
from .invoice_views import (
    CardInvoiceListCreateView,
    InvoiceCancelView,
    InvoiceCreateView,
    InvoiceDetailView,
    InvoiceOriginalView,
    InvoiceRejectView,
    InvoiceVerifyView,
    ModerationInvoiceListView,
    PayoutCreateView,
    PayoutDetailView,
    PayoutWebhookView,
)

urlpatterns = [
    path("api/cards/<int:pk>/expenses/", CardExpenseListCreateView.as_view()),
    path("api/cards/<int:pk>/expenses/public/", CardPublicExpenseReportView.as_view()),
    path("api/cards/<int:pk>/invoices/", CardInvoiceListCreateView.as_view()),
    path("api/moderation/expenses/", ModerationExpenseListView.as_view()),
    path("api/moderation/invoices/", ModerationInvoiceListView.as_view()),
    path("api/expenses/<int:pk>/", ExpenseDetailView.as_view()),
    path("api/expenses/<int:pk>/comments/<int:comment_id>/", ExpenseCommentEditView.as_view()),
    path("api/expenses/<int:pk>/submit/", ExpenseSubmitView.as_view()),
    path("api/expenses/<int:pk>/cancel/", ExpenseCancelView.as_view()),
    path("api/expenses/<int:pk>/original/", ExpenseOriginalView.as_view()),
    path("api/expenses/<int:pk>/approve/", ExpenseApproveView.as_view()),
    path("api/expenses/<int:pk>/reject/", ExpenseRejectView.as_view()),
    path("api/expenses/<int:pk>/request-revision/", ExpenseRequestRevisionView.as_view()),
    path("api/expenses/<int:pk>/request-clarification/", ExpenseRequestRevisionView.as_view()),
    path("api/invoices/", InvoiceCreateView.as_view()),
    path("api/invoices/<int:pk>/", InvoiceDetailView.as_view()),
    path("api/invoices/<int:pk>/original/", InvoiceOriginalView.as_view()),
    path("api/invoices/<int:pk>/verify/", InvoiceVerifyView.as_view()),
    path("api/invoices/<int:pk>/reject/", InvoiceRejectView.as_view()),
    path("api/invoices/<int:pk>/cancel/", InvoiceCancelView.as_view()),
    path("api/payouts/", PayoutCreateView.as_view()),
    path("api/payouts/webhook/<str:provider>", PayoutWebhookView.as_view()),
    path("api/payouts/<int:pk>/", PayoutDetailView.as_view()),
    path("api/admin/expenses/", AdminExpenseListView.as_view()),
    path("internal/cards/<int:pk>/totals/", InternalTotalsView.as_view()),
    path("internal/cards/<int:pk>/reconcile/", InternalReconcileView.as_view()),
    path("internal/expenses/<int:pk>/mark-paid/", InternalMarkPaidView.as_view()),
]
