# Generated by Django 6.0.6 on 2026-06-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='cards/documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('under_review', 'На проверке'), ('verified', 'Проверен'), ('rejected', 'Отклонён')], default='uploaded', max_length=16)),
                ('has_confidential', models.BooleanField(default=False)),
                ('moderator_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cards.fundraisingcard')),
            ],
        ),
    ]
