# Generated by Django 6.0.6 on 2026-06-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.TextField(blank=True)),
                ('document_url', models.FileField(blank=True, null=True, upload_to='cards/expenses/')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=16)),
                ('moderator_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cards.fundraisingcard')),
            ],
        ),
    ]
