# Generated by Django 6.0.6 on 2026-06-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='FundraisingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('clinic', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='cards/photos/')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_moderation', 'На модерации'), ('revision_required', 'Требуется доработка'), ('approved', 'Одобрена'), ('active', 'Активна'), ('rejected', 'Отклонена'), ('completed', 'Завершена'), ('deceased', 'Получатель умер'), ('redistribution', 'Перераспределение средств'), ('archived', 'Архив')], default='draft', max_length=32)),
                ('iin_encrypted', models.CharField(blank=True, max_length=64)),
                ('iin_masked', models.CharField(blank=True, max_length=32)),
                ('document_number_encrypted', models.CharField(blank=True, max_length=64)),
                ('document_number_masked', models.CharField(blank=True, max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('moderator_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
