# Generated by Django 5.2.15 on 2026-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraisingcard',
            options={'ordering': ['-created_at']},
        ),
    ]
