# Generated by Django 5.2.15 on 2026-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Charity Platform', max_length=255)),
                ('demo_payment_enabled', models.BooleanField(default=True)),
                ('bank_integration_stub', models.BooleanField(default=True)),
                ('escrow_integration_stub', models.BooleanField(default=True)),
                ('pdf_auto_check_stub', models.BooleanField(default=True)),
                ('notifications_stub', models.BooleanField(default=True)),
                ('egov_integration_stub', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
